// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function reducer(_state, action) {
  return {
          marker: action[0]
        };
}

function MarkerCmp(Props) {
  var map = Props.map;
  var marker_props = Props.marker_props;
  var children = Props.children;
  var match = React.useReducer(reducer, {
        marker: undefined
      });
  var dispatch = match[1];
  var state = match[0];
  React.useEffect((function () {
          var marker = new (L.marker)(marker_props.location, marker_props.marker_options);
          marker.addTo(map);
          Curry._1(dispatch, /* SetMyMarker */[Caml_option.some(marker)]);
          return (function (param) {
                    marker.removeFrom(map);
                    
                  });
        }), ([]));
  React.useEffect((function () {
          var marker = state.marker;
          if (marker !== undefined) {
            Caml_option.valFromOption(marker).setLatLng(marker_props.location);
          }
          
        }), [marker_props.location]);
  var marker = state.marker;
  return React.createElement(React.Fragment, undefined, marker !== undefined ? Curry._1(children, Caml_option.valFromOption(marker)) : null);
}

var make = MarkerCmp;

exports.reducer = reducer;
exports.make = make;
/* react Not a pure module */
