// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Server = require("react-dom/server");

function PopupCmp(Props) {
  var marker = Props.marker;
  var popupOptions = Props.popupOptions;
  var children = Props.children;
  React.useEffect((function () {
          marker.bindPopup(Server.renderToString(children), popupOptions);
          
        }), /* tuple */[
        [marker],
        children
      ]);
  return React.createElement(React.Fragment, undefined);
}

var make = PopupCmp;

exports.make = make;
/* react Not a pure module */
