// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var MapCmp$ReactHooksTemplate = require("./map-components/MapCmp.bs.js");
var PopupCmp$ReactHooksTemplate = require("./map-components/PopupCmp.bs.js");
var MarkerCmp$ReactHooksTemplate = require("./map-components/MarkerCmp.bs.js");

function ExampleComponent(Props) {
  return React.createElement("div", undefined, React.createElement(MapCmp$ReactHooksTemplate.make, {
                  mapOptions: {
                    map_elem_id: "map_div",
                    options: {
                      center: {
                        lat: 13.0,
                        lng: 77.60
                      },
                      zoom: 12
                    }
                  },
                  children: (function (map) {
                      return React.createElement(MarkerCmp$ReactHooksTemplate.make, {
                                  map: map,
                                  marker_props: {
                                    location: {
                                      lat: 13.0,
                                      lng: 77.60
                                    },
                                    marker_options: undefined
                                  },
                                  children: (function (marker) {
                                      return React.createElement(PopupCmp$ReactHooksTemplate.make, {
                                                  marker: marker,
                                                  popupOptions: {
                                                    close_button: true
                                                  },
                                                  children: React.createElement("div", undefined, "This is a popup")
                                                });
                                    })
                                });
                    })
                }));
}

var make = ExampleComponent;

exports.make = make;
/* react Not a pure module */
