// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/legacy/ReactDOMRe.bs.js");
var ExampleComponent$ReactHooksTemplate = require("./ExampleComponent.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(ExampleComponent$ReactHooksTemplate.make, { }), "index");

/*  Not a pure module */
